### ISSUE TITLE
[FF Win7] [HTML-CSS] highlight does not cover integral (in display block).

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-a11y#133]
Can be seen in Struik. This is a note from the final round of testing. I'm not sure if I saw it elsewhere.

I don't think it's very important but wanted to post it for the record.

**Comment by dpvc** [comment]
The bounding box of the integral sign is only about half its width (the integral sicks out of it) in the MathJax TeX fonts.  This is part of the TeX font data itself, and its purpose (I assume) is so that the integrand will be properly placed under the integral without the need of additional kerning rules, since the integral is such a slanted character (something similar is done for the italic math-mode "f").  The highlighting only highlights the bounding box, not any "ink" that extends beyond that.  A number of characters do extend beyond their boxes, though the integrals are the ones that extend the furthest.

So I think this is currently "expected behavior".  MathJax does maintain information about the extend to which the expression moves beyond the bounding box, so it might be possible to make the highlighting more sophisticated, but currently that is not being done.

**Comment by pkra** [comment]
Thanks, Davide.
