### ISSUE TITLE
Issues with collapsing during exploration  (math.SE)

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-a11y#154]
I was just testing math.stackexchange (e.g [this](http://math.stackexchange.com/questions/1954548/how-do-i-perform-a-first-order-taylor-expansion-on-fracfx-1dx-1fx-2d)) and noticed the following bugs:
- collapsing during walking ends the walker 
- collapsed equations did not get a summary

**Comment by pkra** [comment]
For the record, I saw this on Chrome (Linux) and Firefox (Win7).

**Comment by zorkow** [comment]
1. When you say collapsing, do you mean using keyboard or mouse clicks? In the latter case the walker will indeed stop (can be restarted in the previous position, however, if this position still exists). The problem is that the mouse click can occur anywhere, i.e., on the highlighted element but also above, below or outside. One would therefore have to recompute the walker entirely and it's not even clear how far one would have to walk. We discussed that at the time and decided it is not worse the hassle.

2. Do you mean the aria-label?  I did not see that. (I've been testing with Chrome and Firefox in Linux).
Can you point me to a concrete example where that happens?
Note also that we made sure that summary works well with the MathSpeak rules but the old ChromeVox rules do not necessarily always play together well with the summary rules.

**Comment by pkra** [comment]
> When you say collapsing, do you mean using keyboard or mouse clicks?

Keyboard.

> Do you mean the aria-label?

No. Once I re-entered the walker, it did continue at the collapsed expression but that expression did not get a summary corresponding to the collapse but voiced the entire subexpression.

**Comment by pkra** [comment]
> Can you point me to a concrete example where that happens?

I saw this on math.stackexchange.com. Eg., http://math.stackexchange.com/questions/1972241/lim-x-rightarrow-0-frac1-cos-a-1x-cdot-cos-a-2x-cdot-cos-a-3x-cdo, the limit in the question.

**Comment by zorkow** [comment]
I've played with a number of Browser/OS combinations on SauceLabs and I can not reproduce the problem. Please have a look for yourself. Are we sure that all files are fully purged, caches have been cleared, etc.?
Also, what was the particular error message that you saw?

**Comment by zorkow** [comment]
Well I can also not reproduce the SVG collapse failure locally. However, what I can see is that the mactions in SE don't have any class attribute.  E.g.,
document.getElementsByClassName('mjx-svg-maction');
does not yield any results.
@dpvc is there a setting we are missing? The highlighter relies on the class name being there.
@pkra do we know if SE does something to the SVGs?

**Comment by zorkow** [comment]
OK, classnames also disappear on the MathJax.org website.
And I can see the walker stopping on collapse problem. I have an inkling where it could come from. It's difficult to test as I can't reproduce it locally. 
@pkra I will commit a new sre version (1.1.1) so we can try out. (I might be totally off, however!).

**Comment by zorkow** [comment]
OK, I narrowed down the problem at hand. It is a focus and timing issue, which seems to be introduced by the 'End Math' hook. @dpvc I remember we introduced it for a reason and you refined it. Do you recall exactly what we did there?

**Comment by zorkow** [comment]
Further looking into the problem: It turns out that it is unpredictable (albeit stable) in which order the code executes:
Ideally after the enter keypress in line [480](https://github.com/mathjax/MathJax-a11y/blob/master/extensions/explorer.js#L480) the consequent code [https://github.com/mathjax/MathJax-a11y/blob/master/extensions/explorer.js#L481] should be executed, then the End Math hook would fire (line [331](https://github.com/mathjax/MathJax-a11y/blob/master/extensions/explorer.js#L331)) and reactivate the walker.
However, in some cases the end math event fires before the code block after 480 finishes.
There does not seem to be a particular indicator what the execution order will be, only that it is stable by website. I.e., it does not happen for me SE but on MathJax.org.
All I can guess is that it might have something to do with the speed of the machine (i.e., Peter's is pretty new).
Anyway, we need to get that execution order stable. @dpvc any idea how?

**Comment by dpvc** [comment]
> The highlighter relies on the class name being there.

I believe that SRE adds these class names itself [here](https://github.com/zorkow/speech-rule-engine/blob/master/src/highlighter/svg_highlighter.js#L105).  (The name is set [earlier](https://github.com/zorkow/speech-rule-engine/blob/master/src/highlighter/svg_highlighter.js#L35)).  This class name is not part of the core MathJax code.

I will look into the other issues when I have a moment.

**Comment by dpvc** [comment]
> However, in some cases the end math event fires before the code block after 480 finishes.

That suggests that `MathJax.Hub.Typeset()` is being called somewhere either line 480 or with the block that follows.  Probably in the onclick handler.  It may be that the call to `onclick()` should be wrapped in a `setTimeout()` or that the "End Math" handler should be postponed via `setTimeout()` to allow the block at 481 to complete.

**Comment by pkra** [comment]
@zorkow, is this fixed now? (The commit that mentions this issue says "part of")

**Comment by pkra** [comment]
From a quick test, I believe this was fixed in 1.2.0.
