### ISSUE TITLE
Unexpected identifier (Chrome) and Missing } after property list (Firefox)

### ISSUE THREAD

**Issue by quang-ha** [mathjax/MathJax-a11y#164]
When adding MathJax Accessibility Extensions into Wordpress page, [here](https://www.mathjax.org/mathjax-accessibility-extensions-v1-now-available/), into our `header.php`, using:

```
<script type="text/x-mathjax-config">
	MathJax.Ajax.config.path["Contrib"] = "https://cdn.mathjax.org/mathjax/contrib";
	MathJax.Hub.Config({
	  extensions: ["[Contrib]/a11y/accessibility-menu.js"]
	  menuSettings: {
	    collapsible: true,
	    autocollapse: true,
	    explorer: true
	  }
	});
</script>
<script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
```

There seems to be syntax errors on both Chrome and Firefox (image attached). 
![chrome](https://cloud.githubusercontent.com/assets/6018816/20672843/a8ded6ae-b550-11e6-8772-c604a245cbe2.png)
![firefox](https://cloud.githubusercontent.com/assets/6018816/20672842/a8db28ce-b550-11e6-80be-61974e980657.png)

Is this a bug? Or did we not load some other scripts?

**Comment by dpvc** [comment]
You are missing a comma at the end of the line for `extensions` in your configuration.

**Comment by quang-ha** [comment]
*Facepalm*... thanks!!

**Comment by gnameline** [comment]
Hello, I have a problem running a php page on chrome 58, it has some formulas and can't see the fractions, in firefox I can see them correctly, please could you help me? I only use this for mathjax: 

`    <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      tex2jax: {inlineMath: [["$","$"],["\\(","\\)"]]}
    });
    </script>

    <script type="text/javascript" src="../MathJax.js?config=MML_HTMLorMML-full"></script>`

and this to create my formulas:
<p>
                        <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
                        
                          <mrow>
                            <mfrac>
                                <mrow><mi><i>TEXT HERE</i></mi> </mrow>
                                <mrow><mi><i>OTHER TEXT HERE</i></mi> </mrow>
                            </mfrac>
                          </mrow>
                        </math>
                      </p>

**Comment by dpvc** [comment]
A couple for issues:

1.  Your problem is unrelated to the issue to which you have attached your message.  You should start a new issue tracker for a new problem rather than add to one that has no connection to your problem.

2.  Since you are using the `MML_HTMLorMML-full` configuration, you are not using the `tex2jax` extension, so your `MathJax.Hub.Config()` call is unnecessary, and you can leave out the entire configuration `<script>` .

3.  Your main issue, however, is that MathJax does not allow mixed HTML and MathML, so your use of `<i>` within the fractions is not allowed in MathJax.  You could use `<mtext mathvariant="italic">TEXT HERE</mtext>` instead of `<i>TEXT HERE</i>` if you want italic text as part of the expression.
