### ISSUE TITLE
Enabling auto-collapse without enabling collapsible-math results in undefined variable usage

### ISSUE THREAD

**Issue by mitya57** [mathjax/MathJax-a11y#173]
Steps to reproduce (with Chromium):

* Open any page with math (i.e. one on mathjax.org main page);
* Enable Chromium dev tools;
* Select Accessibility → Auto Collapse.

At this point Chromium warns about undefined variable usage. This happens in [auto-collapse.js:51](https://github.com/mathjax/MathJax-a11y/blob/master/extensions/auto-collapse.js#L51):
```js
MathJax.Extension.collapsible.Enable(false,menu);
```
here `MathJax.Extension.collapsible` is undefined.

**Comment by pkra** [comment]
Thanks for the report!

**Comment by dpvc** [comment]
The auto-collapse extension does load the collapsible extension, but it looks like the `Enable()` function is being called before the other one has finished loading.  I'll have to look into it.  The interconnections among the various components is pretty complicated, since they can be loaded independently or together, and need to load automatically on menu selections, etc.  But something is clearly amiss.

**Comment by dpvc** [comment]
The `issue173` branch includes a patch for this.

**Comment by dpvc** [comment]
==> Merged.
