### ISSUE TITLE
explorer not active after refreshing

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-a11y#197]
Steps to reproduce:

* visit https://cdn.rawgit.com/mathjax/MathJax/2.7.1/test/sample-mml.html
* activate the explorer in the menu
  * explore beautiful, state-of-the-art rendering
* refresh the page 
* focus an equation and <kbd>shift+space</kbd>

Expected: 
* the explorer starts

Actual:
* the MathJax menu opens
* the checkbox a11y/explorer/activate is ticked but no other options are available

![screenshot from 2017-05-24 10-39-57](https://cloud.githubusercontent.com/assets/426686/26394599/bd62094a-406d-11e7-847b-1cab74a0aabf.png)

Workaround:
* hitting the checkbox again activates the explorer

**Comment by pkra** [comment]
Reproduced on Chrome and FF latest.

**Comment by dpvc** [comment]
It turns out that the accessibility-menu extension has a timing problem when used in a combined configuration file.  The combined configuration file runs before the menu cookie is read, the menu settings aren't actually in place when the accessibility-menu code runs, so it doesn't know that the menu items have been selected, so doesn't load the needed code.

I have put a fix in the `issue197` branch.

**Comment by dpvc** [comment]
==> Merged.
