### ISSUE TITLE
empty xmlns causes math processing errors

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-a11y#220]
E.g., 

```
<math xmlns="">   <mi>x</mi> </math>
```

When activating the a11y extensions, there is a processing error. 

(Reproduce on Chrome 62)

**Comment by dpvc** [comment]
OK, this is due to [line 146](https://github.com/mathjax/MathJax-a11y/blob/master/extensions/semantic-enrich.js#L146) in `semantics-enrich` (and the corresponding original `toMathML` extension), which adds a namespace if there isn't one.  But it considers a blank `xmlns` as missing.  I will make a PR for it.
