### ISSUE TITLE
[demos] add links back to GitHub

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-a11y#60]
We should add links to GitHub (e.g., https://github.com/mathjax/MathJax-RespEq/wiki/Support-Matrix-a11y-tool) to the demos.

**Comment by dpvc** [comment]
Which demos do you have in mind for this?

**Comment by pkra** [comment]
All demos, in particular the walker, the Labs but Struik would also benefit to have a note on this so that people can understand what they're seeing.

**Comment by dpvc** [comment]
The labs are out testing platforms, not really intended for public use.  I'm not sure they are the right design for demonstrating or illustrating the tools.  For example, you added some versions with line breaks that were trimmed down, with copyrights and so on.  Examples for public use may still need to be developed.

**Comment by pkra** [comment]
> The labs are out testing platforms, not really intended for public use. 

I suspect we're just thinking about public differently. We already publicized these demos in emails, mailing list postings, reports, blog posts, papers, videos etc. The wiki pages about the project link to them but if you happen to find the demo (e.g., from some random Twitter post) you won't know what they are about or how to use them. A simple link back to GitHub on those pages will help here.

**Comment by zorkow** [comment]
I had not read that issue before merging into gh-pages.
What should we do now? Pages with redirects?

**Comment by dpvc** [comment]
No problem.  Leave the demos as is.  There is no reason not the allow others to use them if they want.  But I just don't feel very compelled to have a lot of documentation for them, since they are for us to use in testing, not really for public examples.

**Comment by pkra** [comment]
> But I just don't feel very compelled to have a lot of documentation for them, since they are for us to use in testing, not really for public examples.

I still disagree here, as argued above.

**Comment by zorkow** [comment]
I've looked at some of our slides and we point to the lab pages.
In the unlikely event that people go through those links we could just add redirects in gh-pages.

As for documentation: we could point to one of the papers. Or alternatively to some of the youtube videos.

**Comment by dpvc** [comment]
> We already publicized these demos

Not me.  ;-)

> if you happen to find the demo (e.g., from some random Twitter post) you won't know what they are about or how to use them

And I'm not particularly concerned about that.  As I said, they are not intended for others, and if others find them, it is really not my job to tell them what they are.  I'm fine with putting a link back to the Github page if you want, but just because someone can find the lab doesn't mean I have to document it for them.  

If I were writing demos for others to use or as examples of how to use the extensions, these probably wouldn't be the ones I'd write.  If you want to put together demos for that purpose, that would be great (though I'd appreciate it if they were in a separate demo folder rather than in the lab folder where I do my work).  If you are interested in writing documentation for how to use those (or even these) demos, that's fine as well.  I'm afraid I don't find your arguments above compelling enough myself, though I certain respect your viewpoint on it.

**Comment by pkra** [comment]
We need to discuss this F2F.
